[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart_ml_cube"
version = "0.1.0"
description = "Keras Federated Learning Quickstart with Flower"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
flwr = "^1.1.0"  # For development: { path = "../../", develop = true }
tensorflow-cpu = "^2.11.0"
mlcube = "0.0.8"
mlcube-docker = "0.0.8"
cookiecutter = "1.7.*"
tensorflow-estimator = "^2.11.0"
