[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "quickstart_pandas"
version = "0.1.0"
description = "Pandas Federated Analytics Quickstart with Flower"
authors = ["Ragy Haddad <ragy202@gmail.com>"]
maintainers = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.8"
flwr = "^1.0.0"
numpy = "^1.21.0"
pandas = "^1.5.2"
scikit-learn = "^1.1.1"
