[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mxnet_example"
version = "0.1.0"
description = "MXNet example with MNIST and CNN"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.7"
flwr = "^1.0.0"
# flwr = { path = "../../", develop = true }  # Development
mxnet = "^1.7.0"
