name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  build_docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build docs
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.15
      - name: Install build tools
        run: |
          sudo apt install pandoc
          python -m pip install -U pip==22.3.1
          python -m pip install -U setuptools==65.6.3
          python -m pip install -U poetry==1.3.2
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Build and deploy docs
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: ./dev/build-docs.sh

  deploy_docs:
    needs: build_docs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy docs
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.15
      - name: Install build tools
        run: |
          sudo apt install pandoc
          python -m pip install -U pip==22.3.1
          python -m pip install -U setuptools==65.6.3
          python -m pip install -U poetry==1.3.2
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Build and deploy docs
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: ./dev/deploy-docs.sh
