name: Release

on:
  schedule:
    - cron: "0 23 * * *"

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  nightly_release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.15
      - name: Install build tools
        run: |
          python -m pip install -U pip==22.3.1
          python -m pip install -U setuptools==65.6.3
          python -m pip install -U poetry==1.3.2
      - name: Release nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./dev/publish-nightly.sh
